name: kami

site:
  favicon: https://s3.bmp.ovh/2026/02/11/Ik3t1Etb.jpg
  # 开屏图 svg 标签，注意 XSS
  logo_svg: null
  # 随机图片
  figure: null

  # 副标题
  subtitle: null

  background:
    src:
      light: /assets/background.png
      dark: /assets/background-night.png
    position: top center fixed

  header:
    menu:
      - title: 源
        path: /
        type: Home
        icon: faDotCircle
        subMenu: []
      - title: 文
        path: /posts
        type: Post
        subMenu: []
        icon: faGlasses
      - title: 记
        type: Note
        path: /notes/latest
        icon: faFeatherAlt
      - title: 言
        path: /says
        icon: faComments
      - title: 览
        icon: faHistory
        path: /timeline
        subMenu:
          - title: 生活
            icon: faFeatherAlt
            path: /timeline?type=note
          - title: 博文
            icon: faBookOpen
            path: /timeline?type=post
          - title: 回忆
            icon: faCircle
            path: /timeline?memory=1
      - title: 友
        icon: faUserFriends
        path: /friends
      - title: 诉
        icon: faComment
        path: /recently
      - title: 余
        icon: faCircleNotch
        path: /favorite/music
        subMenu:
          - title: 项目
            icon: faFlask
            path: /projects

  social:
    - url: 'https://github.com/matto49'
      title: GitHub
      icon: faGithub
      color: var(--black)
    - url: 'https://space.bilibili.com/357923745'
      title: bilibili
      icon: faBilibili
      color: '#12b7f5'

  footer:
    background:
      src:
        dark: ''
        light: /assets/footer.png
      position: top/cover
    home_page: /
    motto:
      content: Ambitious.
    icp:
      enable: true
      label: '赣ICP备2022001149号-1'
      link: https://beian.miit.gov.cn

    navigation:
      - name: 关于
        path: '/about'
      - name: 留言
        path: '/message'
      - name: 友链
        path: '/friends'
      # - name: RSS 订阅
      #   path: '/feed'
      #   newtab: true
      # - name: 站点地图
      #   path: '/sitemap'
      #   newtab: true
      # - name: 开往
      #   path: https://travellings.link/
      #   newtab: true

  custom:
    script: ''
    style: ''
    js: []
    css: []

page:
  home:
    sections:
      - post
      - note
      - friend
      - more
    title_mapping:
      post: ''
      note: ''
      friend: ''
      more: ''
    more:
      - name: 点赞
        type: 'like'
        cover:

function:
  comment:
    disable: false
  player:
    # 默认播放列表
    # 只支持网易云
    id:
      - 563534789
      - 1447327083
      - 1450252250
  analyze:
    enable: false
    ga: ''
    baidu: ''
    umami:
      id: ''
      url: ''
      jsname: 'umami'
      # 这是我魔改版本 umami 专属
      endpoint: 'collect'
      hostUrl: '/'
  donate:
    enable: false
    link: https://afdian.net/@example
    qrcode: []

  ban_devtool:
    enable: false

  notification: {}
